// source: https://www.goodreads.com/quotes/tag/programming
const quotes = [
  { quote: 'Programs must be written for people to read, and only incidentally for machines to execute.', author: 'Harold Abelson'},
  { quote: 'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.', author: 'Rick Cook' },
  { quote: 'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live', author: 'John Woods' },
  { quote: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', author: 'Martin Fowler' },
  { quote: 'Truth can only be found in one place: the code.', author: 'Robert C. Martin' },
  { quote: 'That\'s the thing about people who think they hate computers. What they really hate is lousy programmers.', author: 'Larry Niven' },
  { quote: 'You\'ve baked a really lovely cake, but then you\'ve used dog shit for frosting.', author: 'Steve Jobs' },
  { quote: 'A language that doesn\'t affect the way you think about programming is not worth knowing.', author: 'Alan J. Perlis' },
  { quote: 'The most disastrous Any fool can write code that a computer can understand. Good programmers write code that humans can understand.thing that you can ever learn is your first programming language.', author: 'Alan Kay' },
  { quote: 'The computer programmer is a creator of universes for which he alone is the lawgiver. No playwright, no stage director, no emperor, however powerful, has ever exercised such absolute authority to arrange a stage or field of battle and to command such unswervingly dutiful actors or troops.', author: 'Joseph Weizenbaum' },
  { quote: 'Everyone knows that debugging is twice as hard as writing a program in the first place. So if you\'re as clever as you can be when you write it, how will you ever debug it?', author: 'Brian Kernighan' },
  { quote: 'No matter which field of work you want to go in, it is of great importance to learn at least one programming language.', author: 'Ram Ray' },
  { quote: 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand.', author: 'Martin Fowler' },
  { quote: 'First, solve the problem. Then, write the code', author: 'John Johnson' },
  { quote: 'Experience is the name everyone gives to their mistakes.', author: 'Oscar Wilde' },
  { quote: 'In order to be irreplaceable, one must always be different', author: 'Coco Chanel' },
  { quote: 'Java is to JavaScript what car is to Carpet.', author: 'Chris Heilmann' },
  { quote: 'Knowledge is power', author: 'Francis Bacon' },
  { quote: 'Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code', author: 'Dan Salomon' },
  { quote: 'Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away', author: 'Antoine de Saint-Exupery' },
  { quote: 'Ruby is rubbish! PHP is phpantastic!', author: 'Nikita Popov' },
  { quote: 'Code is like humor. When you have to explain it, it’s bad', author: 'Cory House' },
  { quote: 'Fix the cause, not the symptom', author: 'Steve Maguire' },
  { quote: 'Optimism is an occupational hazard of programming: feedback is the treatment', author: 'Kent Beck' },
  { quote: 'When to use iterative development? You should use iterative development only on projects that you want to succeed', author: 'Martin Fowler' },
  { quote: 'Simplicity is the soul of efficiency.', author: 'Austin Freeman' },
  { quote: 'Before software can be reusable it first has to be usable', author: 'Ralph Johnson' },
  { quote: 'Make it work, make it right, make it fast', author: 'Kent Beck' },
  { quote: "Programming isn't about what you know; it's about what you can figure out", author: 'Chris Pine' },
  { quote: 'The only way to learn a new programming language is by writing programs in it', author: 'Dennis Ritchie' },
  { quote: "Sometimes it's better to leave something alone, to pause, and that's very true of programming", author: 'Joyce Wheeler' },
  { quote: 'Testing leads to failure, and failure leads to understanding', author: 'Burt Rutan' },
  { quote: 'The best error message is the one that never shows up', author: 'Thomas Fuchs' }
];
