// Source: https://www.rd.com/list/challenging-riddles/
const riddles = [
  { question: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?', answer: 'An echo' },
  { question: 'You measure my life in hours and I serve you by expiring. I’m quick when I’m thin and slow when I’m fat. The wind is my enemy. ', answer: 'A Candle' },
  { question: 'I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I? ', answer: 'A Map' },
  { question: 'What is seen in the middle of March and April that can’t be seen at the beginning or end of either month?', answer: 'The letter "R"' },
  { question: 'You see a boat filled with people. It has not sunk, but when you look again you don’t see a single person on the boat. Why?', answer: 'All the people were married' },
  { question: 'What word in the English language does the following: the first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire world signifies a great woman. What is the word?', answer: 'Heroine' },
  { question: 'I’m tall when I’m young, and I’m short when I’m old. What am I?', answer: 'A candle' },
  { question: 'What has to be broken before you can use it?', answer: 'An egg' },
  { question: 'What month of the year has 28 days?', answer: 'All of them' },
  { question: 'What is full of holes but still holds water?', answer: 'A sponge' },
  { question: 'What question can you never answer yes to?', answer: 'Are you asleep yet?' },
  { question: 'What is always in front of you but can’t be seen?', answer: 'The future' },
  { question: 'There’s a one-story house in which everything is yellow. Yellow walls, yellow doors, yellow furniture. What color are the stairs?', answer: ' There aren’t any—it’s a one-story house.' },
  { question: 'What can you break, even if you never pick it up or touch it?', answer: 'A promise' },
  { question: ' What goes up but never comes down?', answer: 'Your age' },
  { question: 'A man who was outside in the rain without an umbrella or hat didn’t get a single hair on his head wet. Why?', answer: 'He was bald.' },
  { question: 'What gets wet while drying?', answer: 'A towel' },
  { question: 'What can you keep after giving to someone?', answer: 'Your word' },
  { question: ' I shave every day, but my beard stays the same. What am I?', answer: ' A barber' },
  { question: 'You see a boat filled with people, yet there isn’t a single person on board. How is that possible?', answer: ' All the people on the boat are married.' },
  { question: ' You walk into a room that contains a match, a kerosene lamp, a candle and a fireplace. What would you light first?', answer: ' The match' },
  { question: 'A man dies of old age on his 25 birthday. How is this possible?', answer: 'He was born on February 29.' },
  { question: ' I have branches, but no fruit, trunk or leaves. What am I?', answer: 'A bank' },
  { question: 'What can’t talk but will reply when spoken to?', answer: 'An echo' },
  { question: 'The more of this there is, the less you see. What is it?', answer: 'Darkness' },
  { question: 'What has lots of eyes, but can’t see?', answer: ' A potato' },
  { question: 'What has one eye, but can’t see?', answer: 'A needle' },
  { question: 'What has many needles, but doesn’t sew?', answer: 'A Christmas tree' },
  { question: 'What has hands, but can’t clap?', answer: 'A clock' },
  { question: 'What has legs, but doesn’t walk?', answer: 'A table' },
  { question: 'What has one head, one foot and four legs?', answer: 'A bed' },
  { question: ' What can you catch, but not throw?', answer: 'A cold' },
  { question: 'What kind of band never plays music?', answer: 'A rubber band' },
  { question: 'What has many teeth, but can’t bite?', answer: ' A comb' },
  { question: 'What is cut on a table, but is never eaten?', answer: 'A deck of cards' },
  { question: 'What has words, but never speaks?', answer: 'A book' },
  { question: 'What runs all around a backyard, yet never moves?', answer: 'A fence' },
  { question: ' What can travel all around the world without leaving its corner?', answer: ' A stamp' },
  { question: 'What has a thumb and four fingers, but is not a hand?', answer: ' A glove' },
  { question: 'What has a head and a tail but no body?', answer: 'A coin' },
  { question: 'Where does one wall meet the other wall?', answer: ' On the corner' },
  { question: ' What building has the most stories?', answer: 'The library' },
  { question: 'What tastes better than it smells?', answer: 'Your tongue' },
  { question: 'What has 13 hearts, but no other organs?', answer: 'A deck of cards' },
  { question: 'It stalks the countryside with ears that can’t hear. What is it?', answer: 'Corn' },
  { question: 'Which is heavier: a ton of bricks or a ton of feathers?', answer: 'Neither—they both weigh a ton.' },
  { question: 'A girl has as many brothers as sisters, but each brother has only half as many brothers as sisters. How many brothers and sisters are there in the family?', answer: 'Four sisters and three brothers' },
  { question: 'What has four wheels and flies?', answer: 'A garbage truck' },
  { question: 'What goes through cities and fields, but never moves?', answer: 'A road' },
  { question: 'People make me, save me, change me, raise me. What am I?', answer: 'Money' },
  { question: 'What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?', answer: 'A river' },
  { question: 'What 4-letter word can be written forward, backward or upside down, and can still be read from left to right?', answer: 'NOON' },
  { question: 'Two in a corner, one in a room, zero in a house, but one in a shelter. What is it?', answer: 'The letter “r”' },
  { question: 'What is the end of everything?', answer: 'The letter “g”' }
];
